on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: cp06.nordicway.dk
          username: ${{ secrets.secrets_username }}
          password: ${{ secrets.secrets_password }}
          server-dir: /cars-r-us.fhallengreen.com/

      - name: Print environment variables
        run: |
          echo $JDBC_URL
          echo $JDBC_USERNAME
          echo $JDBC_PASSWORD
        env:
          JDBC_URL: ${{ secrets.JDBC_URL }}
          JDBC_USERNAME: ${{ secrets.JDBC_USERNAME }}
          JDBC_PASSWORD: ${{ secrets.JDBC_PASSWORD }}

      - name: 📝 Configure application properties
        run: |
          echo "spring.datasource.url=${JDBC_URL}" >> application.yml
          echo "spring.datasource.username=${JDBC_USERNAME}" >> application.yml
          echo "spring.datasource.password=${JDBC_PASSWORD}" >> application.yml
